instagram_clone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^register/',user_views.register,name="register"),
    url('^profile/',user_views.profile,name="profile"),
    url('',include('main.urls')),
    url('^login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    url('^logout',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from .views import (
    # ImageListView,
    ImageDetailView,
    ImageCreateView,
    ImageUpdateView,
    ImageDeleteView,
    OtherProfile,
    ImageSearch,
    Index_View,
    CommentOnImage,
    Like,
)


urlpatterns = [
    url(r'^$',Index_View,name="index_view"),
    url(r'^image/(?P<pk>\d+)$',ImageDetailView.as_view(),name="image_detail"),
    url(r'^image/new$',ImageCreateView.as_view(),name="image_upload"),
    url(r'^image/(?P<pk>\d+)/update',ImageUpdateView.as_view(),name="image_update"),
    url(r'^image/(?P<pk>\d+)/delete',ImageDeleteView.as_view(),name="image_delete"),
    url(r'^user/(?P<pk>\d+)',OtherProfile,name="single_profile"),
    url(r'^search/$',ImageSearch,name="search-results"),
    url(r'^comment/(?P<pk>\d+)',CommentOnImage,name="image-comment"),
    url(r'^like/(?P<pk>\d+)',Like,name="image-like"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Image(models.Model):
    '''
    This model will contain the columns to our image class
    '''
    image = models.ImageField(upload_to='main_photos/')
    image_name = models.CharField(max_length=30)
    image_caption=models.CharField(max_length=300,blank=True)
    profile = models.ForeignKey(User,on_delete=models.CASCADE)

    def get_absolute_url(self):
        '''
        Gets the absolute url for the Image created so as to enable redirect to image created route
        '''
        return reverse('image_detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.image_name

    
    def save_image(self):
        '''
        Saves an Image in the db
        '''
        self.save()

    
    def delete_image(self):
        '''
        Deletes an image model from the db
        '''
        self.delete()

    
    def update_caption(self):
        '''
        Saves a caption from the db
        '''
        pass

    @classmethod
    def search_by_name(self,searched_image):
        '''
        Searches for images using names
        '''
        searched_images = self.objects.filter(image_name__icontains=searched_image)
        return searched_images

class Likes(models.Model):
    '''
    This model will contain the columns to our likes class
    '''
    image_like = models.IntegerField(default=0)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.ForeignKey(Image,on_delete=models.CASCADE)
    
    def __int__(self):
        return self.like


class Comment(models.Model):
    '''
    This model will contain the columns for our comments class
    '''
    comment = models.CharField(max_length=255,null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.ForeignKey(Image,on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

main/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    '''
    create comment form
    '''
    class Meta:
        model = Comment
        exclude = ['user','image']

main/views.py
from django.shortcuts import render,redirect
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from .models import Image,Likes
from users.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import CommentForm


# class ImageListView(LoginRequiredMixin,ListView):
#     '''
#     class based view to display uploaded images
#     '''
#     model = Image
#     template_name = 'main/index.html'
#     context_object_name = 'images'
#     ordering = ['-pk']
@login_required
def Index_View(request):
    '''
    function based view to display index page
    '''
    form = CommentForm()
    all_likes = Likes.objects.all()
    users = User.objects.all()
    images = Image.objects.all().order_by('-pk')
    return render(request,'main/index.html',{'images':images,"form":form,"likes":all_likes,"users":users})

@login_required
def CommentOnImage(request,pk):
    '''
    View for commenting on a specfic image
    '''
    current_user = request.user
    current_image = Image.objects.get(id=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = current_user
            comment.image = current_image
            comment.save()
            return redirect(Index_View)
    else:       
        return redirect(Index_View)

class ImageDetailView(LoginRequiredMixin,DetailView):
    '''
    Class based view for viewing specific image with its details
    '''
    model = Image

# class PersonalProfileView(LoginRequiredMixin,DetailView):
#     pass


@login_required
def OtherProfile(request,pk):
    '''
    Function to display user profile
    '''
    user = User.objects.get(pk=pk)
    users = User.objects.all()
    current_user = request.user
    images = Image.objects.filter(profile=user)
    context = {
        "user":user,
        "images":images,
        "users":users,
        "current_user":current_user
    }
    return render(request,"main/profileview.html",context)


@login_required
def ImageSearch(request):
    '''
    Function to search for images by name
    '''
    if 'image' in request.GET and request.GET['image']:
        searched_image = request.GET.get('image')
        searched_images = Image.search_by_name(searched_image)
        message = f"{searched_image}"
        return render(request,'main/search.html',{"message":message,"images":searched_images,})
    else:
        message = "blank"
        return render(request,'main/search.html',{"messsage":message})


class ImageCreateView(LoginRequiredMixin,CreateView):
    '''
    Class based view for adding new image
    '''
    model = Image
    fields = ['image','image_name','image_caption']

    def form_valid(self,form):
        '''
        form overide to set user who uploaded image
        '''
        form.instance.profile = self.request.user
        return super().form_valid(form)


class ImageUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    '''
    Class based view for updating new image
    '''
    model = Image
    fields = ['image','image_name','image_caption']

    def form_valid(self,form):
        '''
        form overide to set user who uploaded image
        '''
        form.instance.profile = self.request.user
        return super().form_valid(form)

    def test_func(self):
        '''
        Function run by userpassestestmixin to check if user passes test to be able to update image
        '''
        image = self.get_object()
        if self.request.user == image.profile:
            return True
        return False


class ImageDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):

    '''
    class based view to delete image object
    '''
    model = Image
    success_url = '/'

    def test_func(self):
        '''
        Function run by userpassestestmixin to check if user passes test to be able to delete image
        '''
        image = self.get_object()
        if self.request.user == image.profile:
            return True
        return False

@login_required
def Like(request,pk):
    '''
    Implements the like functionality in the app
    '''
    current_user = request.user
    likes = Likes.objects.filter(user=current_user).first()
    if likes == None:
        image = Image.objects.get(pk=pk)
        current_user = request.user
        user_likes = Likes(user=current_user,image=image)
        user_likes.save()
        return redirect(Index_View)
    else:
        likes.delete()
        return redirect(Index_View)

main/templates/main/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block styles %}
        {% bootstrap_css %}
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Cookie&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% endblock %}

    {% if title %}
    <title>Insta-clone - {{ title }}</title>
    {% else %}
    <title>Insta-clone</title>
    {% endif %}

</head>
<body>
    {% include 'main/navbar.html' %}
    
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    
    {% block content %}

    {% endblock %}

    {% block scripts %}
        {% bootstrap_javascript jquery='full' %}
    {% endblock %}
</body>
</html>

main/templates/main/image_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
    <div class="content-section">
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Image</legend>
                <h2>Are you sure you want to delete image {{ object.image_name }}</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a href="{% url 'image_detail' object.id %}" class="btn btn-outline-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>
<div class="col-md-4"></div>
</div>
{% endblock %}

main/templates/main/image_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container"> 
    <div class="row"> 
        <div class="col-md-8">
    <div class="card">
            <div class="card-heading">
                <div class="placing">
            <a href="{% url 'profile' %}"><img src="{{ object.profile.profile.profile_pic.url }}" alt="profile picture" class="rounded-circle custom-display border border-danger"></a>
            <p class="ml-3">{{ image.profile.username }}</p>
            {% if object.profile == user %}
            <div class="float-right">
                <a href="{% url 'image_update' object.id %}" class="btn btn-secondary btn-sm">Update</a>
                <a href="{% url 'image_delete' object.id %}" class="btn btn-danger btn-sm">Delete</a>
            </div>
            {% endif %}
        </div>
            </div><hr>
            <div  class="card-body">
            <a href="{% url 'image_detail' image.id%}"><img src="{{ object.image.url }}" alt="{{ image.image_name }} image" class="display-images img-fluid"></a>
            <p>{{ object.image_name }}: {{ object.image_caption }}</p>
        </div>
        <div class="card-footer">
                {% if object.profile == user %}
                <a href="{% url 'image_update' object.id %}" class="btn btn-secondary btn-sm">Update</a>
                <a href="{% url 'image_delete' object.id %}" class="btn btn-danger btn-sm">Delete</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="col-md-4">
    {% if object.comment_set.all %}
        {% for comment in object.comment_set.all %}
            <p><a href="{% url 'single_profile' comment.user.profile.id %}"><img src="{{ comment.user.profile.profile_pic.url }}" alt="profile picture" class="rounded-circle custom-display border border-danger"></a><strong>{{ comment.user.username }}</strong>:  {{ comment.comment }}</p>
        {% endfor %}
    {% endif %}
</div>
</div> 
</div>

{% endblock %}

main/templates/main/image_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
    <div class="content-section">
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Upload Image</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Upload</button>
            </div>
        </form>
    </div>
</div>
<div class="col-md-4"></div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
        <p class="text-center"><a href="{% url 'image_upload' %}"><i class="fa fa-upload"></i> | Upload Image</a></p>
      {% if images %}
      {% for image in images %}
      <div class="card">
        <div class="card-heading">
          <div class="placing">
            <a href="{% url 'single_profile' image.profile.id %}"><img src="{{ image.profile.profile.profile_pic.url }}"
                alt="profile picture" class="rounded-circle custom-display border border-danger"></a>
            <p class="ml-3">{{ image.profile.username }}</p>
          </div>
        </div>
        <hr>
        <div class="card-body">
          <a href="{% url 'image_detail' image.id%}"><img src="{{ image.image.url }}" alt="{{ image.image_name }} image"
              class="display-images img-fluid"></a>
          <br><br>
          <p>
            <a href="{% url 'image-like' image.id %}"><i class="fa fa-heart"></i></a>
            | {{ image.likes_set.all|length }} <i class="fa fa-comments"></i> | {{ image.comment_set.all|length }}
          </p>
          <p>{{ image.image_caption }}</p><br>
          <p>comments:</p>
          {% if image.comment_set.all %}
          {% for comment in image.comment_set.all|slice:"2" %}
          <p><a href="{% url 'single_profile' comment.user.profile.id %}"><img
                src="{{ comment.user.profile.profile_pic.url }}" alt="profile picture"
                class="rounded-circle custom-display border border-danger"></a><strong>{{ comment.user.username }}</strong>:
            {{ comment.comment }}</p>
          {% endfor %}
          <a href="{% url 'image_detail' image.id %}">
            <p>View all {{ image.comment_set.all|length }} comments</p>
          </a>
          {% endif %}
        </div>
        <div class="card-footer">
          {% if image.profile == user %}
          <button type="button" data-toggle="modal" data-target="#image{{ image.id }}">
            <i class="fa fa-cogs"></i>
          </button>

          <div class="modal fade" id="image{{ image.id }}" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-body">
                  <div class="text-center">
                    <a href="{% url 'image_update' image.id %}">Update</a>
                    <hr>
                    <a href="{% url 'image_delete' image.id %}">Delete</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endif %}
          <form method="POST" class="form-inline" action="{% url 'image-comment'  image.id %}">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn btn-success btn-sm" value="Post">
          </form>
        </div>
      </div><br><br><br>
      {% endfor %}
      {% endif %}
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-4">
      <div class="placing side-view">
        <a href="{% url 'single_profile' user.profile.id %}"><img src="{{ user.profile.profile_pic.url }}"
            alt="profile picture" class="rounded-circle custom-display border border-danger"></a>
        <p class="ml-3">{{ user.profile.user }}</p>
      </div><br><br>
        <div>
          {% if users %}
          <p>Suggested Users</p>
          <div class="overflowstyle">
          {% for reg_user in users %}
          <div class="placing">
              <a href="{% url 'single_profile' reg_user.profile.id %}"><img src="{{ reg_user.profile.profile_pic.url }}"
                  alt="profile picture" class="rounded-circle custom-display border border-danger"></a>
              <p class="ml-3">{{ reg_user.username }}</p>
            </div>
          {% endfor %}
        </div>
          {% endif %}
        </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand h1-custom ml-5" href="/" ><i class="fa fa-instagram"></i> | Instaglam</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        <div class="custom-center">
        <form class="form-inline my-2 my-lg-0" action="{% url 'search-results' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="image">
            <button class="btn btn-outline-success my-2 my-sm-0 hide-button" type="submit">Search</button>
          </form>
        </div>
        <li class="nav-item">
            <a class="nav-link" href="#"><svg aria-label="Find People" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24"><path clip-rule="evenodd" d="M24 .5C37 .5 47.5 11 47.5 24S37 47.5 24 47.5.5 37 .5 24 11 .5 24 .5zm0 44c11.3 0 20.5-9.2 20.5-20.5S35.3 3.5 24 3.5 3.5 12.7 3.5 24 12.7 44.5 24 44.5zm-4.4-23.7c.3-.5.7-.9 1.2-1.2l14.8-8.1c.3-.1.6-.1.8.1.2.2.3.5.1.8l-8.1 14.8c-.3.5-.7.9-1.2 1.2l-14.8 8.1c-.3.1-.6.1-.8-.1-.2-.2-.3-.5-.1-.8l8.1-14.8zm6.2 5l4.3-7.8-7.8 4.3 3.5 3.5z" fill-rule="evenodd"></path></svg></a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#"><svg aria-label="Activity Feed" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24"><path clip-rule="evenodd" d="M34.3 3.5C27.2 3.5 24 8.8 24 8.8s-3.2-5.3-10.3-5.3C6.4 3.5.5 9.9.5 17.8s6.1 12.4 12.2 17.8c9.2 8.2 9.8 8.9 11.3 8.9s2.1-.7 11.3-8.9c6.2-5.5 12.2-10 12.2-17.8 0-7.9-5.9-14.3-13.2-14.3zm-1 29.8c-5.4 4.8-8.3 7.5-9.3 8.1-1-.7-4.6-3.9-9.3-8.1-5.5-4.9-11.2-9-11.2-15.6 0-6.2 4.6-11.3 10.2-11.3 4.1 0 6.3 2 7.9 4.2 3.6 5.1 1.2 5.1 4.8 0 1.6-2.2 3.8-4.2 7.9-4.2 5.6 0 10.2 5.1 10.2 11.3 0 6.7-5.7 10.8-11.2 15.6z" fill-rule="evenodd"></path></svg></a>
          </li>
        <div class="justify-content-end">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <svg aria-label="Profile" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24"><g><path d="M24 27c-7.1 0-12.9-5.8-12.9-12.9s5.8-13 12.9-13c7.1 0 12.9 5.8 12.9 12.9S31.1 27 24 27zm0-22.9c-5.5 0-9.9 4.5-9.9 9.9s4.4 10 9.9 10 9.9-4.5 9.9-9.9-4.4-10-9.9-10zM44 46.9c-.8 0-1.5-.7-1.5-1.5V42c0-5-4-9-9-9h-19c-5 0-9 4-9 9v3.4c0 .8-.7 1.5-1.5 1.5s-1.5-.7-1.5-1.5V42c0-6.6 5.4-12 12-12h19c6.6 0 12 5.4 12 12v3.4c0 .8-.7 1.5-1.5 1.5z"></path></g></svg>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'index_view' %}">Home</a>
            <a class="dropdown-item" href="{% url 'image_upload' %}">Upload image</a>
            <a class="dropdown-item" href="{% url 'single_profile' user.id %}">My Profile</a>
            <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
             </div>
          </div>
        </li>
      </div>
      </ul>
      {% else %}
      <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'login' %}" class="nav-link">Sign In</a>
          </li>
      {% endif %}
    </div>
  </nav>

main/templates/main/profileview.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col-md-12">
    <div class="content-section">
        <div class="media">
            <img src="{{ user.profile.profile_pic.url }}" alt="profile image" class="rounded-circle profile-img">
            <div class="media-body">
                <div class="ml-custom">
                <div class="display">
                <p class="custom-fontsize">{{ user.username }}
                {% if current_user.profile == user.profile %}
                    <a href="{% url 'profile' %}" ><button class="btn btn-outline-primary">Edit Profile</button></a>
                {% endif %}
                <a class="fa fa-sun-o" aria-hidden="true"  data-toggle="modal" data-target="#exampleModalCenter"></a>
            </p>
            <p>
                <i><strong id="pad-left">{{ user.image_set.all|length }}</strong> posts</i>    <i id="pad-left"><strong id="pad-left">{{ users|length}}</strong> followers</i>     <i id="pad-left"><strong >{{ users|length}}</strong> following</i>
            </p>
            </div>
                <p class="text-secondary"> Email: {{ user.email }}</p>
                <p class="text-secondary">Bio: {{ user.profile.bio }}</p>
            </div>
            </div>
        </div>
    </div>
</div>
<!-- <div class="col-md-8"></div> -->
</div><hr>
<div class="row">
    {% if images %}
        {% for image in images %}
        <div class="col-md-4">
            <a href="{% url 'image_detail' image.id %}">
            <img src="{{ image.image.url }}" alt="{{ image.image_name }} image" id="profile-images">
        </a>
        </div>
        {% endfor %}
    {% else %}
        <h2 class="text-center">This user has not uploaded any images yet!!</h2>
    {% endif %}
</div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">

            <div class="modal-body">
                <div class="text-center">
                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>
            </div>
            
          </div>
        </div>
      </div>
{% endblock %}

main/templates/main/search.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            {% if images %}

                <h2>Found {{ images|length }} of searched term {{message}}</h2>
            
            {% else %}

                <h2>Found 0 articles for the search term {{ message }}</h2>
            
            {% endif %}
        </div>
        <div class="row">
                {% if images %}
                {% for image in images %}
                <div class="card">
                    <div class="card-heading">
                        <div class="placing">
                    <a href="{% url 'single_profile' image.profile.id %}"><img src="{{ image.profile.profile.profile_pic.url }}" alt="profile picture" class="rounded-circle custom-display border border-danger"></a>
                    <p class="ml-3">{{ image.profile.username }}</p>
                </div>
                    </div><hr>
                    <div  class="card-body">
                    <a href="{% url 'image_detail' image.id%}"><img src="{{ image.image.url }}" alt="{{ image.image_name }} image" class="display-images img-fluid"></a>
                    <p>{{ image.image_caption }}</p>
                </div>
                <div class="card-footer">
                        {% if image.profile == user %}
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#image{{ image.id }}">
                                <i class="fa fa-cogs"></i>
                              </button>
        
                              <div class="modal fade" id="image{{ image.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                      <div class="modal-content">
                                        <!-- <div class="modal-header">
                                          <h5 class="modal-title" id="exampleModalLongTitle">Picture Update</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                        </div> -->
                                        <div class="modal-body">
                                            <div class="text-center">
                                                <a href="{% url 'image_update' image.id %}">Update</a><hr>
                                                <a href="{% url 'image_delete' image.id %}">Delete</a>
                                            </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                    {% endif %}
                    <!-- <form action="">
        
                    </form> -->
                </div>
                </div><br><br><br>
                {% endfor %}
            {% endif %}  
        </div>
    </div>
{% endblock %}